### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ShehanYjoz** [accurascan/Flutter-AccuraScan-KYC#1]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDevDebugAarMetadata'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Failed to transform AccuraFaceMatch-3.2.0.aar (com.github.accurascan:AccuraFaceMatch:3.2.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not download AccuraFaceMatch-3.2.0.aar (com.github.accurascan:AccuraFaceMatch:3.2.0)
         > Could not get resource 'https://jitpack.io/com/github/accurascan/AccuraFaceMatch/3.2.0/AccuraFaceMatch-3.2.0.aar'.
            > Could not GET 'https://jitpack.io/com/github/accurascan/AccuraFaceMatch/3.2.0/AccuraFaceMatch-3.2.0.aar'. Received status code 401 from server: Unauthorized
   > Failed to transform Liveness-Android-3.2.0.aar (com.github.accurascan:Liveness-Android:3.2.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not download Liveness-Android-3.2.0.aar (com.github.accurascan:Liveness-Android:3.2.0)
         > Could not get resource 'https://jitpack.io/com/github/accurascan/Liveness-Android/3.2.0/Liveness-Android-3.2.0.aar'.
            > Could not GET 'https://jitpack.io/com/github/accurascan/Liveness-Android/3.2.0/Liveness-Android-3.2.0.aar'. Received status code 401 from server: Unauthorized
   > Failed to transform AccuraOCR-5.1.0.aar (com.github.accurascan:AccuraOCR:5.1.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not download AccuraOCR-5.1.0.aar (com.github.accurascan:AccuraOCR:5.1.0)
         > Could not get resource 'https://jitpack.io/com/github/accurascan/AccuraOCR/5.1.0/AccuraOCR-5.1.0.aar'.
            > Could not GET 'https://jitpack.io/com/github/accurascan/AccuraOCR/5.1.0/AccuraOCR-5.1.0.aar'. Received status code 401 from server: Unauthorized

**Comment by ShehanYjoz** [comment]
```
allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io'
            credentials { username 'jp_ssguccab6c5ge2l4jitaj92ek2' }
        }
    }
}

```

**Comment by ShehanYjoz** [comment]
```

    packagingOptions {
        pickFirst 'lib/arm64-v8a/libcrypto.so'
        pickFirst 'lib/arm64-v8a/libssl.so'

        pickFirst 'lib/armeabi-v7a/libcrypto.so'
        pickFirst 'lib/armeabi-v7a/libssl.so'

        pickFirst 'lib/x86/libcrypto.so'
        pickFirst 'lib/x86/libssl.so'

        pickFirst 'lib/x86_64/libcrypto.so'
        pickFirst 'lib/x86_64/libssl.so'

    }
```

**Comment by ShehanYjoz** [comment]
used  ` flutter_accurascan_kyc: ^3.0.6`

**Comment by mahdisomjee123** [comment]
Hello,

The issue you are facing is due to the android dependency not being downloaded properly. 
It usually happens when the maven{} is not placed in the correct position.

Please refer to this demo app's file:- [build.gradle](https://github.com/accurascan/Flutter-AccuraScan-KYC/blob/master/android/build.gradle)
Compare this file with your build.gradle file and check the position of maven{}
