### ISSUE TITLE
flutter_accurascan_kyc version 4.1.0 is not running on android

### ISSUE THREAD

**Issue by neocodegh** [accurascan/Flutter-AccuraScan-KYC#2]
I started getting this error when running on android after upgrading the plugin version to `flutter_accurascan_kyc: ^4.1.0`.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform AccuraOCR-6.1.3.aar (com.github.accurascan:AccuraOCR:6.1.3) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find AccuraOCR-6.1.3.aar (com.github.accurascan:AccuraOCR:6.1.3).
        Searched in the following locations:
            https://jitpack.io/com/github/accurascan/AccuraOCR/6.1.3/AccuraOCR-6.1.3.aar

Here is the output of flutter doctor -v :

`[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6 23G80 darwin-x64, locale en-GB)
    • Flutter version 3.22.3 on channel stable at /Users/icode/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (3 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/icode/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.91.1)
    • VS Code at /Users/icode/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.94.0

[✓] Connected device (4 available)
    • SM A145F (mobile)       • RF8W90CGB2R               • android-arm64  • Android 13 (API 33)
    • iCODE’s iPhone (mobile) • 00008101-000E2D302139001E • ios            • iOS 17.5.1 21F90
    • macOS (desktop)         • macos                     • darwin-x64     • macOS 14.6 23G80 darwin-x64
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 127.0.6533.89
    ! Error: Browsing on the local area network for iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!`

**Comment by accurascan** [comment]
To download our SDK's dependencies, the project must include the auth token in the Android/build.gradle file. The issue you're encountering is due to the missing auth token.

Please refer to our demo app's README file for reference; the link is provided below:
https://github.com/accurascan/Flutter-AccuraScan-KYC?tab=readme-ov-file#1setup-android
Add the following to your build.gradle file:

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io/' }
        maven { url 'https://developer.huawei.com/repo/' } // Add Huawei Maven
        maven {
            url 'https://jitpack.io/'
            credentials { username 'jp_ssguccab6c5ge2l4jitaj92ek2' }
        }
    }
}

**Comment by neocodegh** [comment]
I have the same content in my root build.gradle as what you have but the error still get thrown when building apk. For now I downgraded it back to 4.0.8.
